blank_issues_enabled: false
contact_links:
  - name: ISO Language Code
    url: https://github.com/marcus-evans/ISO-Language-Codes
    about: Please ask and answer questions here.
  - name: Feature Request
    url: https://github.com/marcus-evans/ISO-Language-Codes/issues
    about: Suggest an idea for this project.
